---
- name: add hashicorp gpg key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: add hashicorp repo
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"

- name: install vagrant
  apt:
    state: present
    name:
      - vagrant


# - name: add vagrant plugins
#   become_user: "playground_user"
#   command: "vagrant plugin install {{ item }}"
#   loop:
#     - vagrant-libvirt
#     - vagrant-reload


